### ISSUE TITLE
Two scrollbars on right side

### ISSUE THREAD

**Issue by dfrancis01** [dfrancis01/dfo-richt-project#61]
There are two scroll bars visible remove one.
![image](https://user-images.githubusercontent.com/13628072/169390175-edfb040b-882f-431c-8ed0-ab8fa79fa6e7.png)
Solution something like:
```css
div.wrapper {
  overflow-y: hidden;
}
```
